#!/bin/bash

set -e

npm run build

rm -fr .release && mkdir .release

cp -R lib LICENSE README.md package.json .release

cat package.json | \
  jq 'del(.devDependencies, .scripts, .private)' > .release/package.json

read -p "Do you want to publish this module? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  printf "\nPublishing...\n"
  (cd .release && npm publish)
fi

